// Vollständiger Katalog der von DoesTheDogDie bekannten Themen (topicId -> englischer
// Originalname + deutsche Übersetzung), abgerufen über GET /api/v3/topics. Dient als
// Typgrundlage für `ContentWarningStat.topicId` und als Basis für die Gruppierung
// (siehe FEATURES.md: "Grouped & translated DoesTheDogDie content warnings").
// Die Übersetzung ist für die Detailansicht der einzelnen Themen gedacht (z. B. die
// Disclosure unter den gruppierten Warnungen), nicht für die grobe Gruppierung selbst
// (siehe server/utils/does-the-dog-die-topics.ts).
// DDD kann jederzeit neue Themen ergänzen; unbekannte IDs müssen von Aufrufern als
// Fallback behandelt werden, nicht als Fehler.
export interface DoesTheDogDieTopic {
    id: number;
    name: string;
    nameDe: string;
}

export const doesTheDogDieTopics = [
    { id: 153, name: 'a dog dies', nameDe: 'Ein Hund stirbt' },
    { id: 158, name: 'a kid dies', nameDe: 'Ein Kind stirbt' },
    { id: 161, name: 'there are jump scares', nameDe: 'Es gibt Jumpscares' },
    { id: 164, name: 'someone is burned alive', nameDe: 'Jemand wird bei lebendigem Leib verbrannt' },
    { id: 165, name: 'there are spiders', nameDe: 'Es gibt Spinnen' },
    { id: 167, name: 'there\'s flashing lights or images', nameDe: 'Es gibt Blitzlichteffekte oder schnelle Bildwechsel' },
    { id: 168, name: 'a parent dies', nameDe: 'Ein Elternteil stirbt' },
    { id: 171, name: 'there\'s finger/toe mutilation', nameDe: 'Finger oder Zehen werden verstümmelt' },
    { id: 174, name: 'there are clowns', nameDe: 'Es gibt Clowns' },
    { id: 176, name: 'there are shower scenes', nameDe: 'Es gibt Duschszenen' },
    { id: 177, name: 'there\'s shaving/cutting', nameDe: 'Es wird rasiert oder geschnitten' },
    { id: 180, name: 'there\'s spitting', nameDe: 'Es wird gespuckt' },
    { id: 181, name: 'shaky cam is used', nameDe: 'Wackelkamera wird eingesetzt' },
    { id: 182, name: 'someone is sexually assaulted', nameDe: 'Jemand wird sexuell missbraucht' },
    { id: 183, name: 'a horse dies', nameDe: 'Ein Pferd stirbt' },
    { id: 184, name: 'a car crashes', nameDe: 'Ein Auto verunglückt' },
    { id: 186, name: 'a cat dies', nameDe: 'Eine Katze stirbt' },
    { id: 187, name: 'someone dies by suicide', nameDe: 'Jemand begeht Suizid' },
    { id: 188, name: 'there\'s blood/gore', nameDe: 'Es gibt Blut/Gore' },
    { id: 189, name: 'an animal dies', nameDe: 'Ein Tier stirbt' },
    { id: 190, name: 'needles/syringes are used', nameDe: 'Nadeln/Spritzen kommen vor' },
    { id: 191, name: 'someone drowns', nameDe: 'Jemand ertrinkt' },
    { id: 192, name: 'there\'s a hospital scene', nameDe: 'Es gibt eine Krankenhausszene' },
    { id: 193, name: 'someone uses drugs', nameDe: 'Jemand konsumiert Drogen' },
    { id: 194, name: 'an LGBT person dies', nameDe: 'Eine LGBT-Person stirbt' },
    { id: 195, name: 'there\'s body dysmorphia', nameDe: 'Es geht um Körperdysmorphie' },
    { id: 196, name: 'a dragon dies', nameDe: 'Ein Drache stirbt' },
    { id: 197, name: 'there is sexual content', nameDe: 'Es gibt sexuelle Inhalte' },
    { id: 198, name: 'a plane crashes', nameDe: 'Ein Flugzeug stürzt ab' },
    { id: 199, name: 'someone self harms', nameDe: 'Jemand verletzt sich selbst' },
    { id: 200, name: 'there\'s eye mutilation', nameDe: 'Es gibt Augenverstümmelung' },
    { id: 201, name: 'someone vomits', nameDe: 'Jemand erbricht sich' },
    { id: 202, name: 'there\'s a claustrophobic scene', nameDe: 'Es gibt eine klaustrophobische Szene' },
    { id: 203, name: 'there\'s torture', nameDe: 'Es gibt Folter' },
    { id: 204, name: 'someone has cancer', nameDe: 'Jemand hat Krebs' },
    { id: 205, name: 'electro-therapy is used', nameDe: 'Elektrotherapie wird eingesetzt' },
    { id: 206, name: 'someone has a seizure', nameDe: 'Jemand hat einen Anfall' },
    { id: 207, name: 'there\'s ghosts', nameDe: 'Es gibt Geister' },
    { id: 208, name: 'a person is hit by a car', nameDe: 'Eine Person wird von einem Auto erfasst' },
    { id: 209, name: 'Santa (et al) is spoiled', nameDe: 'Der Weihnachtsmann (o. Ä.) wird als nicht echt entlarvt' },
    { id: 210, name: 'teeth are damaged', nameDe: 'Zähne werden beschädigt' },
    { id: 211, name: 'someone falls to their death', nameDe: 'Jemand stürzt zu Tode' },
    { id: 212, name: 'someone speaks hate speech', nameDe: 'Jemand äußert Hassrede' },
    { id: 213, name: 'there are bugs', nameDe: 'Es gibt Insekten' },
    { id: 214, name: 'there are snakes', nameDe: 'Es gibt Schlangen' },
    { id: 215, name: 'someone miscarries', nameDe: 'Jemand erleidet eine Fehlgeburt' },
    { id: 216, name: 'someone breaks a bone', nameDe: 'Jemand bricht sich einen Knochen' },
    { id: 217, name: 'someone has an eating disorder', nameDe: 'Jemand hat eine Essstörung' },
    { id: 218, name: 'there\'s child abuse', nameDe: 'Es gibt Kindesmissbrauch' },
    { id: 219, name: 'there\'s domestic violence', nameDe: 'Es gibt häusliche Gewalt' },
    { id: 220, name: 'there\'s a mental institution scene', nameDe: 'Es gibt eine Szene in einer psychiatrischen Einrichtung' },
    { id: 221, name: 'there\'s a nuclear explosion', nameDe: 'Es gibt eine Atomexplosion' },
    { id: 222, name: 'the ending is sad', nameDe: 'Das Ende ist traurig' },
    { id: 223, name: 'heads get squashed', nameDe: 'Köpfe werden zerquetscht' },
    { id: 224, name: 'someone is possessed', nameDe: 'Jemand wird besessen' },
    { id: 225, name: 'alcohol abuse', nameDe: 'Alkoholmissbrauch' },
    { id: 226, name: 'someone is misgendered', nameDe: 'Jemand wird misgendert' },
    { id: 227, name: 'there are hangings', nameDe: 'Es gibt Erhängungen' },
    { id: 228, name: 'there\'s childbirth', nameDe: 'Es gibt eine Geburt' },
    { id: 229, name: 'animals are abused', nameDe: 'Tiere werden misshandelt' },
    { id: 230, name: 'there\'s addiction', nameDe: 'Es geht um Sucht' },
    { id: 231, name: 'there\'s dog fighting', nameDe: 'Es gibt Hundekämpfe' },
    { id: 232, name: 'there\'s gun violence', nameDe: 'Es gibt Waffengewalt' },
    { id: 233, name: 'there\'s fat jokes', nameDe: 'Es gibt Witze über Übergewicht' },
    { id: 234, name: 'the black guy dies first', nameDe: 'Die Schwarze Figur stirbt zuerst' },
    { id: 235, name: 'someone has an anxiety attack', nameDe: 'Jemand hat eine Angstattacke' },
    { id: 236, name: 'there are incestuous relationships', nameDe: 'Es gibt inzestuöse Beziehungen' },
    { id: 237, name: 'someone gets gaslighted', nameDe: 'Jemand wird Gaslighting ausgesetzt' },
    { id: 238, name: 'someone has an abortion', nameDe: 'Jemand hat eine Abtreibung' },
    { id: 239, name: 'a pregnant person dies', nameDe: 'Eine schwangere Person stirbt' },
    { id: 240, name: 'someone is buried alive', nameDe: 'Jemand wird lebendig begraben' },
    { id: 241, name: 'someone cheats', nameDe: 'Jemand ist untreu' },
    { id: 242, name: 'someone is stalked', nameDe: 'Jemand wird gestalkt' },
    { id: 243, name: 'someone is kidnapped', nameDe: 'Jemand wird entführt' },
    { id: 244, name: 'there\'s ableist language or behavior', nameDe: 'Es gibt ableistische Sprache oder Verhalten' },
    { id: 245, name: 'someone struggles to breathe', nameDe: 'Jemand bekommt keine Luft' },
    { id: 246, name: 'there\'s antisemitism', nameDe: 'Es gibt Antisemitismus' },
    { id: 247, name: 'there are homophobic slurs', nameDe: 'Es gibt homophobe Beleidigungen' },
    { id: 248, name: 'Autism specific abuse', nameDe: 'Missbrauch speziell gegenüber autistischen Personen' },
    { id: 250, name: 'there\'s amputation', nameDe: 'Es gibt eine Amputation' },
    { id: 251, name: 'someone says the n-word', nameDe: 'Jemand sagt das N-Wort' },
    { id: 252, name: 'there\'s a dead animal', nameDe: 'Es gibt ein totes Tier' },
    { id: 253, name: 'A child\'s dear toy is destroyed', nameDe: 'Das Lieblingsspielzeug eines Kindes wird zerstört' },
    { id: 254, name: 'there\'s cannibalism', nameDe: 'Es gibt Kannibalismus' },
    { id: 255, name: 'There\'s audio gore', nameDe: 'Es gibt verstörende Sounddesign-Effekte (Audio-Gore)' },
    { id: 256, name: 'there is copaganda', nameDe: 'Es gibt Polizei-Verherrlichung (Copaganda)' },
    { id: 257, name: 'someone wets/soils themselves', nameDe: 'Jemand macht sich nass oder in die Hose' },
    { id: 258, name: 'there\'s genital trauma/mutilation', nameDe: 'Es gibt Genitalverletzungen/-verstümmelung' },
    { id: 259, name: 'someone says "I\'ll kill myself"', nameDe: 'Jemand sagt „Ich bringe mich um“' },
    { id: 260, name: 'there\'s misophonia', nameDe: 'Es geht um Misophonie (Geräuschempfindlichkeit)' },
    { id: 261, name: 'a baby cries', nameDe: 'Ein Baby weint' },
    { id: 262, name: 'there are "Man in a dress" jokes', nameDe: 'Es gibt „Mann im Kleid“-Witze' },
    { id: 263, name: 'a mentally ill person is violent', nameDe: 'Eine psychisch kranke Person wird gewalttätig dargestellt' },
    { id: 264, name: 'a baby is stillborn', nameDe: 'Ein Baby kommt tot zur Welt' },
    { id: 265, name: 'someone suffers from PTSD', nameDe: 'Jemand leidet an PTBS' },
    { id: 266, name: 'there is a baby or unborn child', nameDe: 'Es gibt ein Baby oder ungeborenes Kind' },
    { id: 267, name: 'there\'s excessive gore', nameDe: 'Es gibt exzessives Gore' },
    { id: 268, name: 'the fourth wall is broken', nameDe: 'Die vierte Wand wird durchbrochen' },
    { id: 269, name: 'a car honks or tires screech', nameDe: 'Ein Auto hupt oder Reifen quietschen' },
    { id: 270, name: 'someone is homeless', nameDe: 'Jemand ist obdachlos' },
    { id: 271, name: 'someone falls down stairs', nameDe: 'Jemand stürzt eine Treppe hinunter' },
    { id: 272, name: 'the r-slur is used', nameDe: 'Das R-Wort wird verwendet' },
    { id: 273, name: 'a male character is ridiculed for crying', nameDe: 'Eine männliche Figur wird fürs Weinen verspottet' },
    { id: 274, name: 'someone is restrained', nameDe: 'Jemand wird fixiert oder gefesselt' },
    { id: 275, name: 'someone overdoses', nameDe: 'Jemand überdosiert' },
    { id: 276, name: 'someone is sexually objectified', nameDe: 'Jemand wird sexuell objektifiziert' },
    { id: 277, name: 'there\'s a large age gap', nameDe: 'Es gibt einen großen Altersunterschied' },
    { id: 278, name: 'someone has a stroke', nameDe: 'Jemand erleidet einen Schlaganfall' },
    { id: 279, name: 'there are nude scenes', nameDe: 'Es gibt Nacktszenen' },
    { id: 280, name: 'there\'s Achilles Tendon injury', nameDe: 'Es gibt eine Achillessehnenverletzung' },
    { id: 281, name: 'someone asphyxiates', nameDe: 'Jemand erstickt' },
    { id: 282, name: 'someone is crushed to death', nameDe: 'Jemand wird zu Tode gequetscht' },
    { id: 283, name: 'there are 9/11 depictions', nameDe: 'Es gibt Darstellungen von 9/11' },
    { id: 284, name: 'an infant is abducted', nameDe: 'Ein Säugling wird entführt' },
    { id: 285, name: 'a pet dies', nameDe: 'Ein Haustier stirbt' },
    { id: 286, name: 'Someone attempts suicide', nameDe: 'Jemand versucht, sich das Leben zu nehmen' },
    { id: 287, name: 'a minor is sexualized', nameDe: 'Eine minderjährige Person wird sexualisiert' },
    { id: 288, name: 'someone has a chronic illness', nameDe: 'Jemand hat eine chronische Krankheit' },
    { id: 289, name: 'someone sacrifices themselves', nameDe: 'Jemand opfert sich' },
    { id: 290, name: 'there is obscene language/gestures', nameDe: 'Es gibt obszöne Sprache/Gesten' },
    { id: 291, name: 'someone has dementia/Alzheimer\'s', nameDe: 'Jemand hat Demenz/Alzheimer' },
    { id: 292, name: 'someone is sexually assaulted onscreen', nameDe: 'Jemand wird im Bild sexuell missbraucht' },
    { id: 293, name: 'a child is abandoned by a parent or guardian', nameDe: 'Ein Kind wird von einem Elternteil oder einer erziehungsberechtigten Person verlassen' },
    { id: 294, name: 'a minority is misrepresented', nameDe: 'Eine Minderheit wird falsch dargestellt' },
    { id: 295, name: 'there are mannequins', nameDe: 'Es gibt Schaufensterpuppen' },
    { id: 296, name: 'there\'s body horror', nameDe: 'Es gibt Body-Horror' },
    { id: 297, name: 'there are razors', nameDe: 'Es gibt Rasierklingen' },
    { id: 298, name: 'Someone becomes unconscious', nameDe: 'Jemand wird bewusstlos' },
    { id: 299, name: 'someone is drugged', nameDe: 'Jemand wird unter Drogen gesetzt' },
    { id: 300, name: 'there\'s fat suits', nameDe: 'Es werden Fat Suits verwendet' },
    { id: 301, name: 'there\'s bisexual cheating', nameDe: 'Es gibt das Klischee der untreuen bisexuellen Person' },
    { id: 302, name: 'D.I.D. Misrepresentation', nameDe: 'Falsche Darstellung von dissoziativer Identitätsstörung' },
    { id: 303, name: 'there\'s Aphobia', nameDe: 'Es gibt Aphobie (Feindlichkeit gegenüber Asexuellen/Aromantischen)' },
    { id: 304, name: 'the abused becomes the abuser', nameDe: 'Die missbrauchte Person wird selbst zur missbrauchenden Person' },
    { id: 305, name: 'a non-human character dies', nameDe: 'Eine nicht-menschliche Figur stirbt' },
    { id: 306, name: 'there\'s body dysphoria', nameDe: 'Es geht um Körperdysphorie' },
    { id: 307, name: 'there\'s bestiality', nameDe: 'Es gibt Bestialität' },
    { id: 308, name: 'someone is held under water', nameDe: 'Jemand wird unter Wasser gedrückt' },
    { id: 309, name: 'somebody is choked', nameDe: 'Jemand wird gewürgt' },
    { id: 310, name: 'there\'s deadnaming or birthnaming', nameDe: 'Es gibt Deadnaming (Nennung des Geburtsnamens)' },
    { id: 311, name: 'someone dies', nameDe: 'Jemand stirbt' },
    { id: 312, name: 'trypophobic content is shown', nameDe: 'Es werden trypophobie-auslösende Inhalte gezeigt' },
    { id: 313, name: 'a family member dies', nameDe: 'Ein Familienmitglied stirbt' },
    { id: 314, name: 'there are transphobic slurs', nameDe: 'Es gibt transfeindliche Beleidigungen' },
    { id: 315, name: 'sexual assault on men is a joke', nameDe: 'Sexuelle Übergriffe an Männern werden als Witz dargestellt' },
    { id: 316, name: 'there\'s anti-abortion themes', nameDe: 'Es gibt abtreibungsfeindliche Inhalte' },
    { id: 317, name: 'someone loses their virginity', nameDe: 'Jemand verliert seine Unschuld' },
    { id: 318, name: 'someone is watched without knowing', nameDe: 'Jemand wird heimlich beobachtet' },
    { id: 319, name: 'animals were harmed in the making', nameDe: 'Bei den Dreharbeiten wurden Tiere verletzt' },
    { id: 320, name: 'there\'s pedophilia', nameDe: 'Es geht um Pädophilie' },
    { id: 321, name: 'someone is beaten up by a bully', nameDe: 'Jemand wird von einem Mobber verprügelt' },
    { id: 322, name: 'someone is eaten', nameDe: 'Jemand wird gefressen' },
    { id: 323, name: 'there\'s ABA therapy', nameDe: 'Es geht um ABA-Therapie' },
    { id: 324, name: 'there\'s farting', nameDe: 'Es wird gefurzt' },
    { id: 325, name: 'there\'s blackface', nameDe: 'Es gibt Blackfacing' },
    { id: 326, name: 'sexual assault is mentioned', nameDe: 'Ein sexueller Übergriff wird erwähnt' },
    { id: 327, name: 'someone is terminally ill', nameDe: 'Jemand ist unheilbar krank' },
    { id: 328, name: 'a major character dies', nameDe: 'Eine wichtige Figur stirbt' },
    { id: 329, name: 'a priceless artifact is destroyed', nameDe: 'Ein unbezahlbares Artefakt wird zerstört' },
    { id: 330, name: 'there\'s abusive parents', nameDe: 'Es gibt missbräuchliche Eltern' },
    { id: 331, name: 'there\'s decapitation', nameDe: 'Es gibt eine Enthauptung' },
    { id: 332, name: 'there\'s an alligator or crocodile', nameDe: 'Es gibt einen Alligator oder ein Krokodil' },
    { id: 334, name: 'reality is unstable or unhinged', nameDe: 'Die Realität ist instabil oder gerät aus den Fugen' },
    { id: 335, name: 'there\'s natural bodies of water', nameDe: 'Es gibt natürliche Gewässer' },
    { id: 336, name: 'someone has a mental illness', nameDe: 'Jemand hat eine psychische Erkrankung' },
    { id: 337, name: 'there are sharks', nameDe: 'Es gibt Haie' },
    { id: 338, name: 'rabbits are harmed', nameDe: 'Kaninchen werden verletzt' },
    { id: 339, name: 'there are sudden loud noises', nameDe: 'Es gibt plötzliche laute Geräusche' },
    { id: 341, name: 'existentialism is debated', nameDe: 'Es wird über Existenzialismus diskutiert' },
    { id: 342, name: 'a woman gets slapped', nameDe: 'Eine Frau wird geohrfeigt' },
    { id: 343, name: 'someone is stabbed', nameDe: 'Jemand wird erstochen' },
    { id: 345, name: 'there\'s incarceration', nameDe: 'Es geht um Inhaftierung' },
    { id: 346, name: 'there\'s end credits scenes?', nameDe: 'Gibt es eine Szene nach dem Abspann?' },
    { id: 347, name: 'the abused forgives their abuser', nameDe: 'Die missbrauchte Person vergibt der missbrauchenden Person' },
    { id: 348, name: 'someone has a meltdown', nameDe: 'Jemand hat einen Zusammenbruch' },
    { id: 349, name: 'autism is misrepresented', nameDe: 'Autismus wird falsch dargestellt' },
    { id: 350, name: 'an animal is abandoned', nameDe: 'Ein Tier wird ausgesetzt' },
    { id: 351, name: 'religion is discussed', nameDe: 'Es wird über Religion gesprochen' },
    { id: 352, name: 'hands are damaged', nameDe: 'Hände werden verletzt' },
    { id: 353, name: 'someone disabled played by able-bodied', nameDe: 'Eine Figur mit Behinderung wird von einer nicht behinderten Person gespielt' },
    { id: 354, name: 'someone defecates', nameDe: 'Jemand hat Stuhlgang' },
    { id: 355, name: 'an animal is sad', nameDe: 'Ein Tier ist traurig' },
    { id: 356, name: 'there\'s underwater scenes', nameDe: 'Es gibt Unterwasserszenen' },
    { id: 357, name: 'there\'s bedbugs', nameDe: 'Es gibt Bettwanzen' },
    { id: 358, name: 'there\'s menstruation', nameDe: 'Es geht um Menstruation' },
    { id: 359, name: 'a trans person is depicted predatorily', nameDe: 'Eine trans Person wird als übergriffig oder gefährlich dargestellt' },
    { id: 360, name: 'someone\'s mouth is covered', nameDe: 'Jemandem wird der Mund zugehalten' },
    { id: 361, name: 'someone\'s throat is mutilated', nameDe: 'Jemandes Kehle wird verstümmelt' },
    { id: 362, name: 'someone dislocates something', nameDe: 'Jemand erleidet eine Verrenkung' },
    { id: 363, name: 'someone leaves without saying goodbye', nameDe: 'Jemand geht, ohne sich zu verabschieden' },
    { id: 364, name: 'there\'s BDSM', nameDe: 'Es geht um BDSM' },
    { id: 365, name: 'someone is abused with a belt', nameDe: 'Jemand wird mit einem Gürtel misshandelt' },
    { id: 366, name: 'there\'s screaming', nameDe: 'Es wird geschrien' },
    { id: 367, name: 'a woman is brutalized for spectacle', nameDe: 'Eine Frau wird auf reißerische Weise misshandelt' },
    { id: 368, name: 'an LGBT+ person is outed', nameDe: 'Eine LGBT+-Person wird geoutet' },
    { id: 369, name: 'there\'s demons or Hell', nameDe: 'Es gibt Dämonen oder die Hölle' },
    { id: 370, name: 'there\'s dissociation, depersonalization, or derealization', nameDe: 'Es geht um Dissoziation, Depersonalisation oder Derealisation' },
    { id: 371, name: 'there\'s audience participation', nameDe: 'Es gibt Publikumsbeteiligung' },
    { id: 372, name: 'there\'s smoke or haze', nameDe: 'Es gibt Rauch oder Nebel' },
    { id: 373, name: 'there is a tsunami', nameDe: 'Es gibt einen Tsunami' },
    { id: 375, name: 'someone has a heart attack', nameDe: 'Jemand erleidet einen Herzinfarkt' },
    { id: 376, name: 'there\'s flying onstage', nameDe: 'Es gibt Flugeinlagen auf der Bühne' },
    { id: 377, name: 'there\'s entrances from audience', nameDe: 'Es gibt Auftritte aus dem Publikum' },
    { id: 378, name: 'there\'s live gunfire', nameDe: 'Es gibt live abgefeuerte Schüsse auf der Bühne' },
] as const satisfies readonly DoesTheDogDieTopic[];

export type DoesTheDogDieTopicId = typeof doesTheDogDieTopics[number]['id'];

const topicNameById = new Map<number, string>(doesTheDogDieTopics.map(topic => [topic.id, topic.name]));
const topicNameDeById = new Map<number, string>(doesTheDogDieTopics.map(topic => [topic.id, topic.nameDe]));

export function isKnownDoesTheDogDieTopicId(topicId: number): topicId is DoesTheDogDieTopicId {
    return topicNameById.has(topicId);
}

export function getDoesTheDogDieTopicName(topicId: number): string | undefined {
    return topicNameById.get(topicId);
}

export function getDoesTheDogDieTopicNameDe(topicId: number): string | undefined {
    return topicNameDeById.get(topicId);
}
