import type { FooterConfig, NavigationConfig, PageContent } from '~~/types/content';

export const defaultNavigation: NavigationConfig = {
    items: [
        { label: 'Home', path: '/', icon: 'material-symbols:other-houses' },
        { label: 'Programm', path: '/programm', icon: null },
        { label: 'Sommerkino', path: '/sommerkino', icon: null },
        { label: 'Das Kino', path: '/das-kino', icon: null },
        { label: 'Mitmachen', path: '/mitmachen', icon: null },
        { label: 'Anfahrt', path: '/anfahrt', icon: null },
        { label: 'Kooperation', path: '/kooperation', icon: null },
    ],
};

export const defaultFooter: FooterConfig = {
    description: 'Studentisches Programmkino in Dresden. Offen für alle.',
    addressLabel: 'August-Bebel-Straße 20, Dresden',
    addressUrl: 'https://maps.google.com/?q=August-Bebel-Straße+20,+01219+Dresden',
    groups: [
        {
            title: 'Besuch',
            links: [
                { label: 'Programm', to: '/programm', icon: 'material-symbols:calendar-month-rounded' },
                { label: 'Anfahrt', to: '/anfahrt', icon: 'material-symbols:directions-rounded' },
                { label: 'Das Kino', to: '/das-kino', icon: 'material-symbols:theaters-rounded' },
                { label: 'Mitmachen', to: '/mitmachen', icon: 'material-symbols:groups-rounded' },
            ],
        },
        {
            title: 'Kontakt',
            links: [
                { label: 'E-Mail', to: 'mailto:info@kino-im-kasten.de', icon: 'material-symbols:mail-rounded' },
                { label: 'Instagram', to: 'https://www.instagram.com/kinoimkasten/', icon: 'mdi:instagram' },
                { label: 'Mastodon', to: 'https://mastodon.social/@kinoimkasten', icon: 'mdi:mastodon' },
                { label: 'Impressum & Datenschutz', to: '/impressum', icon: 'material-symbols:gavel-rounded' },
            ],
        },
    ],
    bottomLeft: '© Objektiv e.V. · Kino im Kasten',
    bottomRight: 'Filmkultur seit 1993',
};

export const defaultPages: PageContent[] = [
    {
        slug: '',
        title: 'Kino im Kasten',
        description: 'Studentisches Programmkino der TU Dresden. Kostenfreie und günstige Filmabende im Hörsaalzentrum und im Innenhof.',
        theme: 'glow',
        status: 'PUBLISHED',
        blocks: [
            {
                id: 'home-hero',
                type: 'landingHero',
                eyebrow: 'Kino im Kasten Dresden',
                title: 'Filmkultur in Dresden. Kuratiert von Studierenden.',
                lead: 'Kostenfreie und günstige Filmabende im Hörsaalzentrum und im Innenhof. Du musst nicht an der TU studieren, um dabei zu sein.',
                actions: [
                    { label: 'Programm ansehen', to: '/programm', style: 'primary' },
                    { label: 'Sommerkino entdecken', to: '/sommerkino', style: 'secondary' },
                ],
                showNextScreening: true,
            },
            {
                id: 'home-program',
                type: 'programOverview',
                title: 'Danach im KiK',
                offset: 1,
                limit: 2,
                linkLabel: 'Vollständiges Programm',
                linkTo: '/programm',
            },
            {
                id: 'home-story',
                type: 'split',
                title: 'Was dich erwartet',
                body: 'Das Kino im Kasten ist ein studentisch organisiertes Programmkino der TU Dresden. Wir zeigen Filme für alle Gäste, mit Liebe zur Auswahl statt Mainstream-Planung.\n\nIm Semester läuft das Programm im Hörsaalzentrum, im Sommer unter freiem Himmel. Der Fokus bleibt gleich: gute Filme, offene Atmosphäre, niedrige Hürden.',
                linkLabel: 'Anfahrt und Spielort',
                linkTo: '/anfahrt',
                points: [
                    'Offen für alle, auch ohne Campusbezug',
                    'Kuratiertes Wochenprogramm mit wechselnden Schwerpunkten',
                    'Mitmachen im Team über den Objektiv e.V.',
                ],
            },
            {
                id: 'home-network',
                type: 'network',
                socialTitle: 'Social und Feeds',
                socialLinks: [
                    { label: 'facebook', url: 'https://www.facebook.com/kinoimkasten/', icon: 'material-symbols:group-rounded' },
                    { label: 'mastodon', url: 'https://mastodon.social/@kinoimkasten', icon: 'material-symbols:forum-rounded' },
                    { label: 'instagram', url: 'https://instagram.com/kinoimkasten/', icon: 'material-symbols:photo-camera-rounded' },
                    { label: 'letterboxd', url: 'https://letterboxd.com/kinoimkasten/', icon: 'material-symbols:movie-rounded' },
                    { label: 'exmatrikulationsamt', url: 'https://www.exmatrikulationsamt.de/index.php?act=Search&CODE=getalluser&mid=10402', icon: 'material-symbols:newspaper-rounded' },
                    { label: 'iCal', url: 'https://www.kino-im-kasten.de/ical', icon: 'material-symbols:calendar-add-on-rounded' },
                    { label: 'RSS', url: 'https://www.kino-im-kasten.de/rss.xml', icon: 'material-symbols:rss-feed-rounded' },
                ],
                supportTitle: 'Trägerverein und Unterstützung',
                supportText: 'Trägerverein des KiK ist der Objektiv e.V. mit Unterstützung von Partnern in Dresden.',
                supporters: [
                    { label: 'Objektiv e.V.', url: 'https://www.objektiv-dresden.de/', image: '/assets/img/objektiv.png', icon: 'material-symbols:camera-roll-rounded', role: 'Trägerverein' },
                    { label: 'TU Dresden', url: 'https://tu-dresden.de/', image: '/assets/img/TUD.png', icon: null, role: null },
                    { label: 'Studentenwerk Dresden', url: 'https://www.studentenwerk-dresden.de/', image: '/assets/img/stw.svg', icon: null, role: null },
                    { label: 'Bunte Medien', url: 'https://www.kino-im-kasten.de/', image: '/assets/img/buntemedien.png', icon: null, role: null },
                    { label: 'Wir für Sachsen', url: 'https://www.ehrenamt.sachsen.de/foerderung-des-engagements-6922.html', image: '/assets/img/wfs.png', icon: null, role: null },
                ],
            },
        ],
    },
    {
        slug: 'das-kino',
        title: 'Das Kino',
        description: 'Informationen zum KiK, zu Preisen und zur Geschichte des studentischen Programmkinos an der TU Dresden.',
        theme: 'das-kino',
        status: 'PUBLISHED',
        blocks: [
            {
                id: 'das-kino-hero',
                type: 'infoHero',
                eyebrow: 'Kino im Kasten',
                title: 'Das Kino',
                description: 'Informationen zum KiK, zu Preisen und zur Geschichte des studentischen Programmkinos an der TU Dresden.',
                actions: [],
            },
            {
                id: 'das-kino-ueber',
                type: 'markdown',
                title: 'Über das Kino',
                content: 'Etwas außerhalb des TU-Kerngeländes, in der August-Bebel-Straße, befindet sich das Kino im Kasten, kurz KiK. Mit nur wenigen Handgriffen verwandelt sich der frisch sanierte Hörsaal in ein echtes Kino.\n\nHier kann man ab 20:30 Uhr dem Alltag entfliehen und in spannende Filmwelten eintauchen. Bei unserer Filmauswahl liegt der Fokus nicht auf Neuerscheinungen, sondern auf interessanten Filmen aus allen Genres und Zeiten.\n\nNeben dem Semesterprogramm organisieren wir Sonderveranstaltungen, bei denen kreative Musiker:innen Stummfilmklassiker live neu vertonen und junge Filmemacher:innen ein Forum erhalten.',
            },
            {
                id: 'das-kino-preise',
                type: 'markdown',
                title: 'Preise',
                content: '| Ticket | Preis |\n|---|---|\n| Ermäßigter Eintritt | 3,00 Euro |\n| Normaler Eintritt | 4,00 Euro |\n\nWir akzeptieren nur Bargeld. Tickets gibt es nur an der Abendkasse. Der Einlass beginnt, sofern nicht anders kommuniziert, 30 Minuten vor Veranstaltungsbeginn.\n\nMit der KiK-Treuekarte ist jeder vierte Besuch gratis. Bei Kooperationsveranstaltungen gelten abweichende Preise oder freier Eintritt.',
            },
            {
                id: 'das-kino-geschichte',
                type: 'markdown',
                title: 'Geschichte',
                content: 'Das Hörsaalgebäude war ursprünglich Teil der NVA-Militärakademie Friedrich Engels. Nach der Wende übernahm die TU Dresden das Gebäude und im Januar 1993 begann der offizielle Spielbetrieb mit dem Film Spiel mir das Lied vom Tod.\n\nMit Beginn des Sommersemesters 2012 wurden im Gebäudekomplex August-Bebel-Straße umfangreiche Sanierungsarbeiten durchgeführt. Am 16. Mai 2014 konnte das Kino im Kasten seine Wiedereröffnung feiern.',
            },
        ],
    },
    {
        slug: 'mitmachen',
        title: 'Mitmachen',
        description: 'Werde Teil des Teams und gestalte Filmabende, Technik und Programmplanung mit.',
        theme: 'neon-grid',
        status: 'PUBLISHED',
        blocks: [
            {
                id: 'mitmachen-hero',
                type: 'infoHero',
                eyebrow: 'Kino im Kasten',
                title: 'Mitmachen',
                description: 'Werde Teil des Teams und gestalte Filmabende, Technik und Programmplanung mit. Egal aus welchem Studiengang du kommst.',
                actions: [
                    { label: 'Mail schreiben', to: 'mailto:info@kino-im-kasten.de', style: 'primary' },
                    { label: 'Programm ansehen', to: '/programm', style: 'secondary' },
                ],
            },
            {
                id: 'mitmachen-worum',
                type: 'markdown',
                title: 'Worum es geht',
                content: 'Wir sind eine bunt gemischte Gruppe aus Studierenden, die seit 1993 das KiK betreibt. Du brauchst kein Vorwissen, nur Lust auf Teamarbeit und Filmkultur.\n\nDu kannst in Technik, Programm, Gastronomie oder Kommunikation einsteigen. Wir arbeiten immer in Tandems, damit der Einstieg leicht bleibt.',
            },
            {
                id: 'mitmachen-rollen',
                type: 'cardGrid',
                title: 'Rollen im Team',
                cards: [
                    { title: 'Filmvorführung', text: 'Digitale und 35mm Projektion, Abendkasse und Gästeservice.', meta: '3 bis 4 Stunden pro Einsatz' },
                    { title: 'Programmplanung', text: 'Filme sichten, Semesterreihen kuratieren und Rechte abstimmen.', meta: '2 bis 4 Stunden pro Woche in Spitzenzeiten' },
                    { title: 'Öffentlichkeitsarbeit', text: 'Texte, Social Media, Aushang und Kommunikation rund um Spieltermine.', meta: '4 bis 5 Stunden pro Monat' },
                    { title: 'Gastro und Abendbetrieb', text: 'Getränke, Knabbereien und Ablauf vor Ort während der Vorstellung.', meta: '1 Abend pro Monat als Einstieg möglich' },
                ],
            },
            {
                id: 'mitmachen-einstieg',
                type: 'markdown',
                title: 'So steigst du ein',
                content: '1. **Kontakt aufnehmen:** Schreib an info@kino-im-kasten.de mit 2 bis 3 Sätzen zu deinem Interesse.\n2. **Kennenlernabend:** Du kommst zu einer Vorstellung, schaust hinter die Kulissen und lernst das Team kennen.\n3. **Erster Einsatz im Tandem:** Beim ersten Termin arbeitest du mit einer erfahrenen Person zusammen.',
            },
            {
                id: 'mitmachen-vorteile',
                type: 'markdown',
                title: 'Deine Vorteile',
                content: '- Kostenlose Filmvorführausbildung inklusive 35mm-Einführung\n- Mitentscheidung beim Semesterprogramm und bei Sonderreihen\n- Eintritt frei bei deinen Einsätzen, inklusive Freigetränk\n- Praxis in Organisation, Technik und Kulturarbeit',
            },
            {
                id: 'mitmachen-kontakt',
                type: 'markdown',
                title: 'Kontakt',
                content: 'Schreib uns an [info@kino-im-kasten.de](mailto:info@kino-im-kasten.de) oder sprich uns direkt bei einer Vorstellung an.\n\nAnsprechpartner:innen: Dana Bruckner und Marvin Eckert.',
            },
        ],
    },
    {
        slug: 'anfahrt',
        title: 'Anfahrt',
        description: 'So findest du den Weg zum Kino im Kasten im TU-Gebäude ABS in der August-Bebel-Straße.',
        theme: 'das-kino',
        status: 'PUBLISHED',
        blocks: [
            {
                id: 'anfahrt-hero',
                type: 'infoHero',
                eyebrow: 'Kino im Kasten',
                title: 'Anfahrt',
                description: 'So findest du den Weg zum Kino im Kasten im TU-Gebäude ABS in der August-Bebel-Straße.',
                actions: [],
            },
            {
                id: 'anfahrt-adresse',
                type: 'markdown',
                title: 'Adresse',
                content: 'Das Kino befindet sich im großen Hörsaal des TU-Gebäudes ABS.\n\nKino im Kasten, August-Bebel-Straße 20, 01219 Dresden.',
            },
            {
                id: 'anfahrt-karte',
                type: 'image',
                title: null,
                src: 'https://www.kino-im-kasten.de/public/map.png',
                alt: 'Anfahrtskarte zum Kino im Kasten',
                caption: null,
            },
            {
                id: 'anfahrt-rad-auto',
                type: 'markdown',
                title: 'Mit dem Fahrrad und Auto',
                content: 'Parkmöglichkeiten sind entlang der Straße vorhanden.',
            },
            {
                id: 'anfahrt-oepnv',
                type: 'markdown',
                title: 'Bus und Bahn',
                content: '- Strehlener Platz: Straßenbahnlinie 11, Buslinie 66\n- Wasaplatz: Straßenbahnlinien 9 und 13, Buslinien 61, 63, 68 und 85\n- Weberplatz: Buslinie 66\n- S-Bf. Strehlen: S1 und S2\n\nVerbindungsauskunft: [DVB Fahrplanauskunft](https://www.dvb.de/de-de/hl?id=2000poiID%3A2104107173%3A14612000%3A-1%3AKino%20im%20Kasten%3ADresden%3AKino%20im%20Kasten%3AANY%3APOI%3A1531015%3A5373156%3AMRCV%3AVVO)',
            },
        ],
    },
    {
        slug: 'sommerkino',
        title: 'Sommerkino',
        description: 'Sommerkino im Innenhof des Fritz-Förster-Baus mit wöchentlichen Open-Air-Filmabenden.',
        theme: 'sommerkino',
        status: 'PUBLISHED',
        blocks: [
            {
                id: 'sommerkino-hero',
                type: 'infoHero',
                eyebrow: 'Open Air im Innenhof',
                title: 'Sommerkino',
                description: 'Freitagabend, Leinwandlicht und Sommerluft: Gemeinsam mit dem StuRa zeigen wir Filme unter freiem Himmel auf dem Campus.',
                actions: [
                    { label: 'Programm ansehen', to: '/programm', style: 'primary' },
                    { label: 'Innenhof finden', to: 'https://maps.google.com/?q=Fritz-F%C3%B6rster-Bau+Dresden', style: 'secondary' },
                ],
            },
            {
                id: 'sommerkino-intro',
                type: 'split',
                title: 'Open Air auf dem Campus',
                body: 'Im Sommer zieht das Kino im Kasten aus dem Hörsaal in den Innenhof des Fritz-Förster-Baus. Dort zeigen wir gemeinsam mit dem Studierendenrat der TU Dresden freitagabends ausgewählte Filme.\n\nDer Eintritt ist bei den regulären Sommerkino-Abenden frei. Komm rechtzeitig, bring gern eine Decke mit und mach es dir auf der Wiese bequem.',
                linkLabel: null,
                linkTo: null,
                points: [
                    'Freitags im Innenhof des Fritz-Förster-Baus',
                    '50 StuRa-Liegen, danach freie Platzwahl auf der Wiese',
                    'Bei Regen oder Sturm ziehen wir ins Kino im Kasten um',
                ],
            },
            {
                id: 'sommerkino-programm',
                type: 'programOverview',
                title: 'Sommerkino-Programm',
                offset: 0,
                limit: 6,
                venueFilter: 'Innenhof',
                linkLabel: 'Vollständiges Programm',
                linkTo: '/programm',
            },
            {
                id: 'sommerkino-besuch',
                type: 'markdown',
                title: 'Für deinen Besuch',
                content: '- **Einlass:** In der Regel 30 Minuten vor Filmbeginn. Die genaue Uhrzeit steht beim jeweiligen Termin.\n- **Mitbringen:** Eine Decke, Mückenschutz und etwas Warmes für später am Abend.\n- **Sprachen:** Wir zeigen deutsche Fassungen sowie Originalfassungen mit deutschen oder englischen Untertiteln.\n- **Wetter:** Bei Regen oder Sturm findet die Vorstellung zur gleichen Zeit im Kino im Kasten statt.',
            },
        ],
    },
    {
        slug: 'kooperation',
        title: 'Kooperation',
        description: 'Hinweise für Kooperationsveranstaltungen im Kino im Kasten von Filmvorführung bis Diskussionsabend.',
        theme: 'neon-grid',
        status: 'PUBLISHED',
        blocks: [
            {
                id: 'kooperation-hero',
                type: 'infoHero',
                eyebrow: 'Kino im Kasten',
                title: 'Kooperation',
                description: 'Hinweise für Kooperationsveranstaltungen im Kino im Kasten von Filmvorführung bis Diskussionsabend.',
                actions: [
                    { label: 'Kooperation anfragen', to: 'mailto:info@kino-im-kasten.de?subject=Kooperationsanfrage%20Kino%20im%20Kasten', style: 'primary' },
                ],
            },
            {
                id: 'kooperation-plan',
                type: 'markdown',
                title: 'Plant ihr eine Kooperationsveranstaltung',
                content: 'Von Filmvorführung über Poetry-Slam bis Konzertabend haben wir vielfältige Erfahrung im Bereich der Veranstaltungsorganisation.',
            },
            {
                id: 'kooperation-ablauf',
                type: 'markdown',
                title: 'Typischer Ablauf',
                content: '1. **Frühzeitig anfragen**\n   Meldet euch am besten ein Semester vor eurem Wunschtermin mit eurer Idee. Deadline: 30. Juni für das Wintersemester und 31. Dezember für das Sommersemester.\n\n2. **Programm und Rechte klären**\n   Wenn noch kein Film feststeht, unterstützen wir euch bei Recherche, Rechtebuchung und der Beschaffung des Vorführmediums.\n\n3. **Veranstaltung gemeinsam umsetzen**\n   Am Abend selbst ist Raum für Einführung oder Diskussion. Die Basistechnik stellen wir, zusätzliche Technik wie extra Bühnenlicht ist optional zubuchbar.',
            },
            {
                id: 'kooperation-kosten',
                type: 'markdown',
                title: 'Kosten',
                content: '| Bereich | Richtwert |\n|---|---|\n| Filmmiete | circa 100 bis 150 Euro |\n| Vorführpauschale (uninahe Institutionen) | 50 Euro |\n| Vorführpauschale (uniexterne Institutionen und Privatpersonen) | 100 Euro |\n| Zusatztechnik (z. B. extra Bühnenlicht) | Technikpauschale 50 Euro |\n\nDie genaue Filmmiete hängt von Verleih, Filmalter, erwarteten Zuschauerzahlen, Eintrittsmodell und Vorführformat ab.\n\nWir recherchieren die finalen Kosten vorab und können bei Bedarf in Vorkasse gehen.\n\nIn der Regel ist eine Kooperation für eine Veranstaltung vorgesehen, bei Reihen oder größeren Themenkomplexen sind bis zu drei Termine möglich.',
            },
            {
                id: 'kooperation-kontakt',
                type: 'markdown',
                title: 'Kontakt',
                content: 'Wenn ihr Lust auf eine Kooperation habt und noch Fragen offen sind, meldet euch über [info@kino-im-kasten.de](mailto:info@kino-im-kasten.de).\n\nSchreibt kurz dazu, welches Format ihr plant, welchen Zeitraum ihr euch wünscht und ob bereits ein Film feststeht.\n\nInformationen zur Bildschirmwerbung für Clubs des Dresdner VDSC und Freunde des Hauses folgen auf einer separaten Seite.',
            },
        ],
    },
    {
        slug: 'impressum',
        title: 'Impressum',
        description: 'Rechtliche Angaben, Datenschutzinformationen und Kontaktadressen von Objektiv e.V. - Kino im Kasten.',
        theme: 'das-kino',
        status: 'PUBLISHED',
        blocks: [
            {
                id: 'impressum-hero',
                type: 'infoHero',
                eyebrow: 'Kino im Kasten',
                title: 'Impressum',
                description: 'Rechtliche Angaben, Datenschutzinformationen und Kontaktadressen von Objektiv e.V. - Kino im Kasten.',
                actions: [],
            },
            {
                id: 'impressum-verein',
                type: 'markdown',
                title: 'Objektiv e.V. - Kino im Kasten',
                content: 'Kraftwerk Mitte 30, 01067 Dresden\n\nVorstand: Niels Beer, Karsten Fritz, Steffi Karn\n\nAmtsgericht Dresden, VR 3024\n\nJugendschutz: Fabian Schauren, jugendschutz@kommunale-kinos.de\n\nSpendenkonto: DE86 8505 0300 0221 2582 72, Ostsächsische Sparkasse Dresden',
            },
            {
                id: 'impressum-datenschutz',
                type: 'markdown',
                title: 'Datenschutzerklärung',
                content: '1. Datenübermittlung und Datenprotokollierung: Beim Besuch dieser Seite verzeichnet der Webserver automatisch Log-Files. Diese Daten werden nur zur statistischen Auswertung gesammelt und nicht an Dritte weitergegeben.\n2. Nutzung persönlicher Daten: Personenbezogene Daten werden nur erhoben, wenn du diese freiwillig mitteilst. Eine Weitergabe erfolgt nur bei gesetzlicher Pflicht.\n3. Auskunft, Änderung und Löschung: Du kannst jederzeit schriftlich Auskunft zu gespeicherten personenbezogenen Daten erhalten.\n4. Sicherheit: Technische und organisatorische Maßnahmen schützen bereitgestellte Daten vor unberechtigtem Zugriff.\n5. Cookies: Session-Cookies dienen der Nutzungserleichterung und werden nach Browserende gelöscht.\n6. YouTube: Bei eingebetteten Videos kann eine Verbindung zu YouTube Servern hergestellt werden. Details unter google.de/intl/de/policies/privacy.\n7. Vimeo: Bei eingebetteten Videos kann eine Verbindung zu Vimeo Servern hergestellt werden. Details unter vimeo.com/privacy.\n8. Änderungen: Diese Datenschutzbestimmungen können bei Bedarf aktualisiert werden.\n\nBei Fragen zu diesen Datenschutzbestimmungen nutze bitte den Kontakt.',
            },
            {
                id: 'impressum-kontakt',
                type: 'markdown',
                title: 'Kontakt',
                content: 'Anschrift (Post und Paket): TU Dresden, Kino im Kasten, Helmholtzstr. 10, 01069 Dresden\n\nBesuchsadresse: Kino im Kasten, August-Bebel-Straße 20, 01219 Dresden\n\nRechnungsadresse: Objektiv e.V. - Kino im Kasten, Kraftwerk Mitte 30, 01067 Dresden\n\nTel.: +49 351 463-36463, Fax: +49 351 463-37300\n\nE-Mail: info@kino-im-kasten.de\n\nInternet: kino-im-kasten.de',
            },
        ],
    },
];
