import type { DoesTheDogDieTopicId } from '../../types/does-the-dog-die-topics';

// Handful of German group labels that the raw DDD topics (see
// types/does-the-dog-die-topics.ts) collapse into on the public program page,
// instead of showing all ~200 narrow English topics verbatim.
// See FEATURES.md: "Grouped & translated DoesTheDogDie content warnings".
export const doesTheDogDieWarningGroups = [
    'gewalt',
    'tod',
    'suizid',
    'sexuell',
    'tiere',
    'substanzen',
    'psyche',
    'medizinisch',
    'diskriminierung',
    'phobien',
    'schwangerschaft',
    'sonstiges',
] as const;

export type DoesTheDogDieWarningGroup = typeof doesTheDogDieWarningGroups[number];

export const doesTheDogDieWarningGroupLabels: Record<DoesTheDogDieWarningGroup, string> = {
    gewalt: 'Gewalt & Verletzungen',
    tod: 'Tod & Sterben',
    suizid: 'Suizid & Selbstverletzung',
    sexuell: 'Sexuelle Inhalte & Übergriffe',
    tiere: 'Tiere',
    substanzen: 'Substanzkonsum & Sucht',
    psyche: 'Psychische Gesundheit',
    medizinisch: 'Medizinische Inhalte',
    diskriminierung: 'Diskriminierung & sensible Sprache',
    phobien: 'Phobien & sensorische Trigger',
    schwangerschaft: 'Schwangerschaft, Geburt & Kinder',
    sonstiges: 'Weitere Inhaltshinweise',
};

// Jeder bekannte DDD-Topic bekommt hier bewusst eine Gruppe zugewiesen; die
// Fallback-Gruppe greift nur für topicIds, die DDD künftig neu hinzufügt und
// die diese Liste noch nicht kennt (siehe getDoesTheDogDieWarningGroup).
const fallbackGroup: DoesTheDogDieWarningGroup = 'sonstiges';

const warningGroupByTopicId: Partial<Record<DoesTheDogDieTopicId, DoesTheDogDieWarningGroup>> = {
    153: 'tiere',
    158: 'tod',
    161: 'phobien',
    164: 'gewalt',
    165: 'phobien',
    167: 'phobien',
    168: 'tod',
    171: 'gewalt',
    174: 'phobien',
    176: 'sonstiges',
    177: 'gewalt',
    180: 'sonstiges',
    181: 'phobien',
    182: 'sexuell',
    183: 'tiere',
    184: 'gewalt',
    186: 'tiere',
    187: 'suizid',
    188: 'gewalt',
    189: 'tiere',
    190: 'medizinisch',
    191: 'gewalt',
    192: 'medizinisch',
    193: 'substanzen',
    194: 'tod',
    195: 'psyche',
    196: 'tiere',
    197: 'sexuell',
    198: 'gewalt',
    199: 'suizid',
    200: 'gewalt',
    201: 'medizinisch',
    202: 'phobien',
    203: 'gewalt',
    204: 'medizinisch',
    205: 'medizinisch',
    206: 'medizinisch',
    207: 'sonstiges',
    208: 'gewalt',
    209: 'sonstiges',
    210: 'gewalt',
    211: 'tod',
    212: 'diskriminierung',
    213: 'phobien',
    214: 'phobien',
    215: 'schwangerschaft',
    216: 'gewalt',
    217: 'psyche',
    218: 'gewalt',
    219: 'gewalt',
    220: 'psyche',
    221: 'gewalt',
    222: 'sonstiges',
    223: 'gewalt',
    224: 'sonstiges',
    225: 'substanzen',
    226: 'diskriminierung',
    227: 'gewalt',
    228: 'schwangerschaft',
    229: 'tiere',
    230: 'substanzen',
    231: 'tiere',
    232: 'gewalt',
    233: 'diskriminierung',
    234: 'diskriminierung',
    235: 'psyche',
    236: 'sexuell',
    237: 'psyche',
    238: 'schwangerschaft',
    239: 'schwangerschaft',
    240: 'gewalt',
    241: 'sonstiges',
    242: 'gewalt',
    243: 'gewalt',
    244: 'diskriminierung',
    245: 'medizinisch',
    246: 'diskriminierung',
    247: 'diskriminierung',
    248: 'diskriminierung',
    250: 'gewalt',
    251: 'diskriminierung',
    252: 'tiere',
    253: 'sonstiges',
    254: 'gewalt',
    255: 'phobien',
    256: 'diskriminierung',
    257: 'sonstiges',
    258: 'gewalt',
    259: 'suizid',
    260: 'phobien',
    261: 'schwangerschaft',
    262: 'diskriminierung',
    263: 'diskriminierung',
    264: 'schwangerschaft',
    265: 'psyche',
    266: 'schwangerschaft',
    267: 'gewalt',
    268: 'sonstiges',
    269: 'phobien',
    270: 'sonstiges',
    271: 'gewalt',
    272: 'diskriminierung',
    273: 'diskriminierung',
    274: 'gewalt',
    275: 'substanzen',
    276: 'sexuell',
    277: 'sonstiges',
    278: 'medizinisch',
    279: 'sexuell',
    280: 'gewalt',
    281: 'gewalt',
    282: 'gewalt',
    283: 'gewalt',
    284: 'schwangerschaft',
    285: 'tiere',
    286: 'suizid',
    287: 'sexuell',
    288: 'medizinisch',
    289: 'sonstiges',
    290: 'sonstiges',
    291: 'medizinisch',
    292: 'sexuell',
    293: 'schwangerschaft',
    294: 'diskriminierung',
    295: 'phobien',
    296: 'gewalt',
    297: 'phobien',
    298: 'medizinisch',
    299: 'substanzen',
    300: 'diskriminierung',
    301: 'diskriminierung',
    302: 'diskriminierung',
    303: 'diskriminierung',
    304: 'gewalt',
    305: 'tiere',
    306: 'psyche',
    307: 'sexuell',
    308: 'gewalt',
    309: 'gewalt',
    310: 'diskriminierung',
    311: 'tod',
    312: 'phobien',
    313: 'tod',
    314: 'diskriminierung',
    315: 'sexuell',
    316: 'schwangerschaft',
    317: 'sexuell',
    318: 'sonstiges',
    319: 'tiere',
    320: 'sexuell',
    321: 'gewalt',
    322: 'gewalt',
    323: 'diskriminierung',
    324: 'sonstiges',
    325: 'diskriminierung',
    326: 'sexuell',
    327: 'medizinisch',
    328: 'tod',
    329: 'sonstiges',
    330: 'gewalt',
    331: 'gewalt',
    332: 'phobien',
    334: 'sonstiges',
    335: 'phobien',
    336: 'psyche',
    337: 'phobien',
    338: 'tiere',
    339: 'phobien',
    341: 'sonstiges',
    342: 'gewalt',
    343: 'gewalt',
    345: 'sonstiges',
    346: 'sonstiges',
    347: 'gewalt',
    348: 'psyche',
    349: 'diskriminierung',
    350: 'tiere',
    351: 'sonstiges',
    352: 'gewalt',
    353: 'diskriminierung',
    354: 'sonstiges',
    355: 'tiere',
    356: 'phobien',
    357: 'phobien',
    358: 'medizinisch',
    359: 'diskriminierung',
    360: 'gewalt',
    361: 'gewalt',
    362: 'gewalt',
    363: 'sonstiges',
    364: 'sexuell',
    365: 'gewalt',
    366: 'phobien',
    367: 'gewalt',
    368: 'diskriminierung',
    369: 'sonstiges',
    370: 'psyche',
    371: 'sonstiges',
    372: 'phobien',
    373: 'gewalt',
    375: 'medizinisch',
    376: 'sonstiges',
    377: 'sonstiges',
    378: 'gewalt',
};

export function getDoesTheDogDieWarningGroup(topicId: number): DoesTheDogDieWarningGroup {
    return warningGroupByTopicId[topicId as DoesTheDogDieTopicId] ?? fallbackGroup;
}
